"""Stable finding codes. The repair router maps from these, so they are an API."""
from __future__ import annotations

ALIGN_CAPACITY_SHORT = "ALIGN_CAPACITY_SHORT"
ALIGN_AREA_OVERFLOW = "ALIGN_AREA_OVERFLOW"
ALIGN_BUDGET_EXCEEDED = "ALIGN_BUDGET_EXCEEDED"
ALIGN_SCHEDULE_EXCEEDED = "ALIGN_SCHEDULE_EXCEEDED"
ALIGN_ZONE_MISSING = "ALIGN_ZONE_MISSING"

COH_EXCLUDES_VIOLATION = "COH_EXCLUDES_VIOLATION"
COH_REQUIRES_UNMET = "COH_REQUIRES_UNMET"
COH_TENSION_UNRECONCILED = "COH_TENSION_UNRECONCILED"
COH_FIDELITY = "COH_FIDELITY"
COH_SOURCE_NAMED = "COH_SOURCE_NAMED"

FEAS_SPAN_EXCEEDED = "FEAS_SPAN_EXCEEDED"
FEAS_COST_BAND = "FEAS_COST_BAND"
FEAS_BUILD_DAYS = "FEAS_BUILD_DAYS"
FEAS_MATERIAL_STRUCTURE_INCOMPATIBLE = "FEAS_MATERIAL_STRUCTURE_INCOMPATIBLE"
FEAS_CLIMATE_INCOMPATIBLE = "FEAS_CLIMATE_INCOMPATIBLE"

CULT_SACRED_MISSING = "CULT_SACRED_MISSING"
CULT_ABSTRACTION_FLOOR = "CULT_ABSTRACTION_FLOOR"
CULT_RESTRICTED_VALUE = "CULT_RESTRICTED_VALUE"

# Cultural findings are never auto-repaired: the system must not attempt to fix a
# ritual or appropriation error by mutation (spec R-REP-01).
NO_AUTO_REPAIR = {CULT_SACRED_MISSING, CULT_RESTRICTED_VALUE}
